### ISSUE TITLE
Documentation available?

### ISSUE THREAD

**Issue by ma7555** [Voice-Lab/VoiceLab#1]
Hello, was interested to know if there is documentation available to understand what exactly is this doing?

Thanks

**Comment by drfeinberg** [comment]
Yes. Here: https://voice-lab.github.io/VoiceLab/On Jul. 1, 2020 9:17 a.m., ma7555 <notifications@github.com> wrote:
Hello, was interested to know if there is documentation available to understand what exactly is this doing?
Thanks
