### ISSUE TITLE
Unable to update default for CPP

### ISSUE THREAD

**Issue by reubebe** [Voice-Lab/VoiceLab#11]
I am unable to change the default settings for the "Tilt line. qeufrency upper bound " I want to change ut to 0.05 but the "." is not responding
![Screen Shot 2022-07-21 at 8 34 39 PM](https://user-images.githubusercontent.com/38767286/180337365-c3056c20-6de4-4cf7-a686-e47969b9e298.png)

**Comment by drfeinberg** [comment]
Sorry. Just seeing this now. Which version are you using? I believe this has already been fixed in the repo but I haven't compiled new binaries for windows and mac yet.

**Comment by reubebe** [comment]
That will be amazing. Thank you. I believe the latest version

**Comment by drfeinberg** [comment]
It's out now.  Sorry it took so long.

**Comment by reubebe** [comment]
Awesome. Thanks
