### ISSUE TITLE
Example code fails with results dictionary containing 'voice'

### ISSUE THREAD

**Issue by ManilaKodali** [Voice-Lab/VoiceLab#13]
I am running the following code on the example wav file provided in the GitHub repository and encoutering the errors.
This is the example code that was taken from the website that I am trying to run:
```
from Voicelab.toolkits.Voicelab.MeasurePitchNode import MeasurePitchNode

measure_pitch_node = MeasurePitchNode()
measure_pitch_node.args['file_path'] = "tmp.wav"
results = measure_pitch_node.process()
print(results['Mean Pitch (F0) (Praat To Pitch (ac))'])
```
tmp.wav is the sample file in the Github repository. 
The output is : 
`voice`
If I print the contents of `results` dictionary above, I get the following output: 
```
{'Pitch': "'voice'",
 'Pitch Values (Praat To Pitch (ac))': "'voice'",
 'Mean Pitch (F0) (Praat To Pitch (ac))': "'voice'",
 'Median Pitch (F0) (Praat To Pitch (ac))': "'voice'",
 'Standard Deviation Pitch (F0) (Praat To Pitch (ac)': "'voice'",
 'Pitch Min (F0) (Praat To Pitch (ac))': "'voice'",
 'Pitch Max (F0) (Praat To Pitch (ac))': "'voice'",
 'Pitch (Praat To Pitch (ac))': "'voice'",
 'Pitch Floor': "'voice'",
 'Pitch Ceiling': "'voice'"}
```
I am running the python code in the same virtual environment as the UI application, I am getting the correct results in the `python voicelab.py` application. 

Is there a way I can get this working?

**Comment by drfeinberg** [comment]
I've completely changed the back end but I did not have a chance to update the documentation, so that won't work on v1.3, but would likely work on v1.2. Also tmp.wav is not a sample sound but something VoiceLab saves out if someone uses an mp3 file. Give it a shot in v1.2.
