### ISSUE TITLE
GUI Version Crashing

### ISSUE THREAD

**Issue by heleusbrands** [Voice-Lab/VoiceLab#14]
First off, great job. Appreciate all your hard work. 

Second, before I get into the issue, thought I'd let ya know I've been working on project that uses VoiceLab's python bindings, and to make things easier on myself, I've been converting your settings dicts into settings classes, as well as unifying all the analysis and manipulation classes into a single class, so it's easier to run multiple tasks on a file, by using a single object. In case this is something you'd be interested in incorporating into the library, I thought I'd offer to send it your way when it's done. If not, definitely no worries! 

Now on to the issue! 

I downloaded the new version today, having used the previous version on a different machine, and loaded up a few sound files. Everything went fine until I tried saving the data, after which the program crashed. I went back in to test if it was just a fluke, and see if there was anything else that was bugging out, and turns out that the "Play Sound(s)" button and "Expand Spectrogram" button don't work either. Essentially, nothing is currently working for me other than loading the sounds, and changing the settings. 

Now, since I am running it on a different machine than the previous version, I can't be sure that it's the new release, and not just some bug with this computer's interaction with the software (until I try one of the previous releases on this comp), but I thought I'd let you know, seeing as it was just updated.

**Comment by drfeinberg** [comment]
That's cool you are working on the API. I'd love to see the changes you made. I haven't really made the API easy to use yet.

What OS are.you using and what happens when you press start? Are you using stereo sounds?

Yes. The spectrogram viewer hasn't worked for a long time.

**Comment by drfeinberg** [comment]
That's cool you are working on the API. I'd love to see the changes you made. I haven't really made the API easy to use yet.

Yes. The spectrogram viewer hasn't worked for a long time.

I've identified the bug in the create spectrogram node. It will probably be a week before I can fix it and push a new version. So if you want to use it now, make sure you don't select spectrograms. Even unselecting Create Spectrogram will cause a crash.

**Comment by drfeinberg** [comment]
I have isolated and fixed the bug where saving spectrograms and power spectra crash the program.  I'll have a look at the play button.

**Comment by drfeinberg** [comment]
I have fixed the spectrogram display.  I'll compile and re-release this.  

I'm not sure what the problem is with the play button.  I can't get any errors with the play button.  It plays sounds every time I press it.

**Comment by heleusbrands** [comment]
Wonderful! Thank you for the speedy responses, I'll download the latest release, test it out, and let ya know! 

And as far as the API modifications go, I'll let you know when I've got it finished up and working within my project. Right now the idea that I've been working with, is creating a config class with the defaults for each analysis or modification class. Those configs are then augmented with some ez adjust options, for commonly switched parameters (i.e. the pitch Algorithm used for the pitch analysis), in the form of Enum subclasses. This way changing those settings becomes as easy as config.Algorithm = PitchAlgorithms.CC.

**Comment by drfeinberg** [comment]
This is all fixed.  The new version was released today.
