### ISSUE TITLE
API Code Examples

### ISSUE THREAD

**Issue by stphnpwrs** [Voice-Lab/VoiceLab#16]
So first off, awesome work, this is a really cool project. 

Second, this is not my forte and I may have missed something vital, so please ignore me if I did something wrong. I think something's missing in the example code for the API. The documentation states that the `args['voice']` is a `parselmouth.Sound` objected, but the nodes treat it as a tuple of the Sound object values and the sample rate (lines 45 and 46 in `ManipulateLowerPitchandFormantsNode.py` for example). To get it to work, I had to add the following lines to the example code in the API to create the sound object, then decompose to the values and sample rate (for the node to use those to recompile to a Sound object). 
```python
import parselmouth
from Voicelab.toolkits.Voicelab.ManipulateLowerPitchAndFormantsNode import ManipulateLowerPitchAndFormantsNode

lower_pitch_and_formants_node = ManipulateLowerPitchAndFormantsNode()
lower_pitch_and_formants_node.args['file_path'] = "./voice.wav"

# Explicitly adding the data
sound = parselmouth.Sound(lower_pitch_and_formants_node.args['file_path'])
lower_pitch_and_formants_node.args['voice'] = sound.values, sound.sampling_frequency

results = lower_pitch_and_formants_node.process()
results['voice'].save(file_path='voice-lower-pitch.wav', format='WAV')
```

Again, awesome project! Thanks!

**Comment by drfeinberg** [comment]
I really haven't finished the API yet. I'll see what I can put together for the next release. Sorry about that. It should work in the GUI of that helps in the meantime.

**Comment by drfeinberg** [comment]
I've put out a new release today.  I made some new examples in the docs.
