### ISSUE TITLE
Version not diplayed or reported

### ISSUE THREAD

**Issue by Trebicky** [Voice-Lab/VoiceLab#17]
Hello,
Congrats on a beautiful piece of software. I am a delighted user.

I am working on a manuscript where I want to report that I used VoiceLab to analyse voice recordings. I would love to report the version I used, but the software does not state or report the version anywhere. And the Help link goes to http://voicelab/help/index.html.

IMHO, it would be helpful to see which version I am running or report the version used in the settings output file.

**Comment by drfeinberg** [comment]
Hi Trebicky,
I'll fix that in the next update.
For now, I can help you find the version number.  Are you using windows, mac, or linux?  
Best,
David

**Comment by Trebicky** [comment]
Thank you. No need, I eventually digged out the downloaded archive and
based on the date I found the version.

It only feels like a good info to have for potential differences between
versions.

Dne st 24. 5. 2023 18:18 uživatel David R. Feinberg <
***@***.***> napsal:

**Comment by drfeinberg** [comment]
Awesome!  I'll make an about page with the version and some citation info, and fix the help link.
