### ISSUE TITLE
Help link in Windows fails

### ISSUE THREAD

**Issue by LorenAmelang** [Voice-Lab/VoiceLab#3]
The Help button in the Windows version calls up
http://voicelab/help/index.html
(in Internet Explorer, which is not my default browser!)
That link is invalid. 

I presume it should go to:
https://voice-lab.github.io/VoiceLab/
Which is very helpful...

**Comment by drfeinberg** [comment]
Thanks!  I'll try to fix this in the next edition.  It was trying to link to a local copy of the help file, but I did not embed it properly for compiling.

**Comment by drfeinberg** [comment]
Hi. It's all fixed... A while back linking to the website.
