### ISSUE TITLE
Just crashes

### ISSUE THREAD

**Issue by DillFrescott** [Voice-Lab/VoiceLab#8]
When attempting to use a manipulate setting on Windows

**Comment by drfeinberg** [comment]
Is there any more info you can give me? I'll have a look into this asap.

**Comment by DillFrescott** [comment]
Sure! I'm trying to shift the formant of some vocals, and when I click play it can't even play my mp3, and when I try to process the formant shift the gui just closes.

**Comment by drfeinberg** [comment]
Ok. Got it. I'll see what I can do.

**Comment by drfeinberg** [comment]
I've been able to fix both issues on my machine.  I will push a new release next week. I'll let you know as soon as it's ready.

**Comment by DillFrescott** [comment]
Hey don't mean to rush at all, but is the release almost ready? I'm just excited to try it out! :)

**Comment by drfeinberg** [comment]
I will get to it as soon as I can. Thank you for your patience while I'm recovering from being sick.

**Comment by DillFrescott** [comment]
Gotcha! Take your time and feel better!

**Comment by drfeinberg** [comment]
I'm working on it now.  I found another bug where it couldn't manipulate stereo files, so that's fixed now too.  I've just got to update the documentation, and then I should be able to compile it and release it.

**Comment by DillFrescott** [comment]
Sounds good!

**Comment by drfeinberg** [comment]
It's up now. Let me know if you have any issues or would like to see any new features.

**Comment by DillFrescott** [comment]
@drfeinberg Thank you sir! I can't wait to try it out! I'll let you know if I find any more issues!

**Comment by DillFrescott** [comment]
@drfeinberg Just tried to raise the pitch of a sound file up 8 semitones and it crashed again.

**Comment by drfeinberg** [comment]
Ok. I'll take a look and fix it up. Thanks for your patience with me and the software. 


Get 
Outlook for Android

**Comment by drfeinberg** [comment]
I've got this working again on my machine.  I'm going to do some extra tests to double check this.

**Comment by drfeinberg** [comment]
The tests are complete and I fixed a couple more issues that I hadn't seen.  I'll compile this asap and make a new version for you.  Compiling usually takes a whole afternoon, but I'm hoping it will go quicker since I've got all the configs sorted last week.

**Comment by DillFrescott** [comment]
Excellent! Sounds good!

**Comment by drfeinberg** [comment]
The new version is up and ready to go!

**Comment by vonBlasberg** [comment]
This looks amazing and I'm excited to try the app. Unfortunately, the app crashes as soon as I press the "Start Queue" button with any audio file (MacOS 12.1.).

**Comment by drfeinberg** [comment]
Ok  I'll take a look.

**Comment by drfeinberg** [comment]
I can't seem to get that to happen.  I'm on the same version of macOS also.  Can you tell me more about the files you are trying?  Are they mono? Stereo?  mp3? wav?

**Comment by drfeinberg** [comment]
Maybe even send me a file at feinberg@mcmaster.ca if you can share them

**Comment by drfeinberg** [comment]
I do know of a bug where it crashes on save if you're measuring energy or subharmonics. I'm working on fixing that now, but not when you just run it....

**Comment by drfeinberg** [comment]
That's been fixed in v1.1.2. please let me know if you're still having issues.
